#pragma once

#include "Pipeline.h"
#include "Node.h"
#include "Inlet.h"
#include "Outlet.h"
#include "Common.h"
#include "Data.h"
#include "GeneratorSineWave.h"
#include "OutputConsolePrinter.h"
#include "NodeKinect.h"
#include "NodeAccumulator.h"
#include "NodeRenderer.h"
#include "NodeOscOut.h"
#include "NodeFilter.h"